### PR TITLE
Print Albums with Bands

### PR DESCRIPTION
**Pull request by hbiede**

### CODE REVIEW

**Comment by cbourke** [comment]
Have you verified this works?  I suspect your lambda expression won't work because we haven't overridden the equals method in the Band class.

**Comment by hbiede** [comment]
I had tested it, but forgot to include that in this public branch. Fixed

**Comment by cbourke** [comment]
Note that any time you override the equals method you should override the hashcode method to operate on the same data/state or there is no guarantee collections will store the objects correctly.

**Comment by hbiede** [comment]
Yes, I always try to. I was being lazy there since it usually auto generates the hash function when I select equals but didn’t this time.

**Pull request merged**
